
server:
  port:
    6969

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      client:
        registration:
          google:
            #google cloud console

            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${GOOGLE_REDIRECT_URL:http://localhost:4200/auth/google/callback}"
            user-info-uri: http://www.googleapis.com/oauth2/v3/userinfo
            resource-server:
              opaque-token:
                introspection-uri: "http://www.googleapis.com"
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "${FACEBOOK_REDIRECT_URL:http://localhost:4200/auth/facebook/callback}"
            auth-uri: http://www.facebook.com/v22.0/v3/dialog/oauth
            token-uri: http://www.graph.facebook.com/oauth/access_token
            user-info-uri: http://www.graph.facebook.com/me?fields=id,name,email,picture.type(large)
            scope:
              - email
              - public_profile


api:
  prefix: api/v1

jwt:
  expiration: 2592000 #30 days: 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days: 30 * 24 * 60 * 60
  secretKey: 2bBXzdplW1CbCQqvzmHApdmM91XrxbrJqtgUfQJSEWk=

#logging.level.org.springframework.security: DEBUG